# Generated by Django 3.2.4 on 2021-06-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='proImgForBrands', verbose_name='Accessories photo')),
                ('fullName', models.CharField(max_length=50, null=True, verbose_name='Full name')),
                ('intro', models.TextField(max_length=200, null=True, verbose_name='Introduction')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=20, null=True, verbose_name='Brand Name')),
            ],
        ),
        migrations.AddField(
            model_name='brands',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='brandImg',
            field=models.ImageField(blank=True, null=True, upload_to='iamges', verbose_name='brand image'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='des',
            field=models.TextField(max_length=500, null=True, verbose_name='Brand description'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='slogan',
            field=models.CharField(max_length=50, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='subTitle',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='TrailCamPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.CharField(max_length=10, null=True, verbose_name='Abbreviation')),
                ('proImg', models.ImageField(blank=True, null=True, upload_to='proImgForBrands', verbose_name='Photo of product')),
                ('modelName', models.CharField(max_length=50, null=True, verbose_name='Model full name')),
                ('des1', models.CharField(max_length=10, null=True)),
                ('des2', models.CharField(max_length=10, null=True)),
                ('des3', models.CharField(max_length=10, null=True)),
                ('briefIntro', models.CharField(max_length=20, null=True, verbose_name='brief introduciton')),
                ('intro', models.TextField(max_length=800, null=True, verbose_name='Detailed introduction')),
                ('proImgBack', models.ImageField(blank=True, null=True, upload_to='proImgForBrands', verbose_name='Back photo of product')),
                ('proImgOpen', models.ImageField(blank=True, null=True, upload_to='proImgForBrands', verbose_name='Openned photo of product')),
                ('imgRes', models.CharField(max_length=100, null=True, verbose_name='Imgae resolution')),
                ('vedRes', models.CharField(max_length=100, null=True, verbose_name='Vedio resolution')),
                ('vedLen', models.CharField(max_length=50, null=True, verbose_name='Vedio Length')),
                ('hybridMode', models.CharField(max_length=50, null=True, verbose_name='Hybrid Mode')),
                ('screen', models.CharField(max_length=50, null=True, verbose_name='Screen')),
                ('detRan', models.CharField(max_length=50, null=True, verbose_name='Detection Range')),
                ('illumination', models.CharField(max_length=50, null=True, verbose_name='Illumination')),
                ('illRan', models.CharField(max_length=50, null=True, verbose_name='Illumination Range')),
                ('triSpe', models.CharField(max_length=50, null=True, verbose_name='Trigger speed')),
                ('SmartIR', models.CharField(max_length=50, null=True, verbose_name='Smart IR')),
                ('imaCol', models.CharField(max_length=100, null=True, verbose_name='Image color')),
                ('mulShoPerTri', models.CharField(max_length=50, null=True, verbose_name='Multi shop per trigger')),
                ('mulShoRat', models.CharField(max_length=50, null=True, verbose_name='Multi shot rate')),
                ('infoBar', models.CharField(max_length=100, null=True, verbose_name='Information bar')),
                ('deley', models.CharField(max_length=50, null=True, verbose_name='Delay')),
                ('opeTim', models.CharField(max_length=50, null=True, verbose_name='Operation time')),
                ('shuSet', models.CharField(max_length=50, null=True, verbose_name='Shutter setting')),
                ('isoSet', models.CharField(max_length=50, null=True, verbose_name='Iso setting')),
                ('timLapSet', models.CharField(max_length=50, null=True, verbose_name='Time-Lapse setting')),
                ('timLapInt', models.CharField(max_length=50, null=True, verbose_name='Time-Lapse interval')),
                ('cardType', models.CharField(max_length=50, null=True, verbose_name='Memory card type')),
                ('carCap', models.CharField(max_length=50, null=True, verbose_name='Memory card capacity')),
                ('memCon', models.CharField(max_length=50, null=True, verbose_name='Memory card configuration')),
                ('batLif', models.CharField(max_length=50, null=True, verbose_name='Battery life')),
                ('batTypQua', models.CharField(max_length=50, null=True, verbose_name='Battery type and Quantity')),
                ('opeTem', models.CharField(max_length=50, null=True, verbose_name='Operation temperature')),
                ('focAdj', models.CharField(max_length=50, null=True, verbose_name='Customization focus range')),
                ('demoVedioDay', models.URLField(null=True, verbose_name='Youtube link of demo vedio in daytime')),
                ('demoVedioNight', models.URLField(null=True, verbose_name='Youtube link of demo vedio at night')),
                ('acc', models.ManyToManyField(blank=True, to='fwscsc.Accessories')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fwscsc.brands')),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fwscsc.supplier'),
        ),
    ]
