# Generated by Django 3.2.4 on 2021-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0002_auto_20210613_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailcampro',
            name='acc',
        ),
        migrations.AddField(
            model_name='accessories',
            name='forPro',
            field=models.ManyToManyField(blank=True, to='fwscsc.TrailCamPro'),
        ),
    ]
