# Generated by Django 3.2.4 on 2021-06-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0003_auto_20210613_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='forPro',
        ),
        migrations.AddField(
            model_name='trailcampro',
            name='acc',
            field=models.ManyToManyField(blank=True, to='fwscsc.Accessories'),
        ),
    ]
