# Generated by Django 3.2.4 on 2021-06-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0004_auto_20210613_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='Img',
            new_name='img',
        ),
    ]
