# Generated by Django 3.2.4 on 2021-06-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0005_rename_img_accessories_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailcampro',
            name='dayIframeTag',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='trailcampro',
            name='nightIframeTag',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
