# Generated by Django 3.2.4 on 2021-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0006_auto_20210614_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(max_length=15, null=True)),
                ('noRecruitment', models.TextField(max_length=10)),
                ('recposition', models.TextField(max_length=20, null=True)),
                ('briefIntro', models.TextField(max_length=20, null=True)),
                ('aboutJob', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
