# Generated by Django 3.2.4 on 2021-06-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0007_recruitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recruitment',
            old_name='recposition',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='noRecruitment',
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fwscsc.brands'),
        ),
    ]
