# Generated by Django 3.2.4 on 2021-06-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0008_auto_20210616_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fwscsc.department'),
        ),
    ]
