# Generated by Django 3.2.4 on 2021-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0009_alter_recruitment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='briefIntro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
