# Generated by Django 3.2.4 on 2021-06-17 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwscsc', '0014_alter_department_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='TrailCamBrand',
        ),
    ]
